version: "3.9"

services:
  mysql-db:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpwd
      MYSQL_DATABASE: service_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - template-network

  service:
    build:
      context: ./template
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./template:/opt/app:delegated
      - ./template/package.json:/opt/package.json
      - ./template/package-lock.json:/opt/package-lock.json
      - ./template/node_modules:/opt/app/node_modules
    networks:
      - template-network

volumes:
  db_data:

networks:
  template-network:
    driver: bridge
